# Generated by Django 5.2 on 2025-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0002_alter_manutentor_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='sn',
            field=models.CharField(max_length=20),
        ),
    ]
